In [2]:
import pandas as pd
df = pd.read_csv("data/final.csv", sep = "\t")
df

,Unnamed: 0,City,County,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape1,Robbery,Aggravated\nassault,Property\ncrime,...,medinc_23p2,medinc_23p3,medinc_23p4,medinc_23p5,medinc_23p6,medinc_23p7,medinc_23p8,Total Students,Free and reduced lunch,Income
0,0,Akron,Summit,197882.0,1782.0,27.0,181.0,328.0,1246.0,6568.0,...,69500.0,78200.0,86800.0,93800.0,100700.0,107700.0,114600.0,513.971631,91.730496,45018.0
1,1,Alliance,Stark,21536.0,28.0,0.0,4.0,1.0,23.0,558.0,...,64000.0,71950.0,79900.0,86350.0,92750.0,99150.0,105500.0,523.047170,117.820755,42092.0
2,2,Amherst,Lorain,12166.0,4.0,0.0,0.0,3.0,1.0,147.0,...,72400.0,81400.0,90400.0,97700.0,104900.0,112100.0,119400.0,497.034483,121.908046,76463.0
3,3,Ashland,Ashland,20410.0,33.0,1.0,18.0,2.0,12.0,384.0,...,63500.0,71400.0,79300.0,85700.0,92000.0,98400.0,104700.0,355.050000,119.350000,52598.0
4,4,Aurora,Portage,16319.0,1.0,0.0,0.0,0.0,1.0,128.0,...,69500.0,78200.0,86800.0,93800.0,100700.0,107700.0,114600.0,429.000000,109.062500,98253.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,Westerville,Franklin,40903.0,74.0,3.0,18.0,16.0,37.0,767.0,...,79400.0,89300.0,99200.0,107200.0,115100.0,123100.0,131000.0,504.110512,112.582210,105371.0
108,108,Wickliffe,Lake,12758.0,16.0,0.0,6.0,2.0,8.0,174.0,...,72400.0,81400.0,90400.0,97700.0,104900.0,112100.0,119400.0,552.142857,185.714286,68690.0
109,109,Willoughby,Lake,23081.0,19.0,0.0,5.0,5.0,9.0,321.0,...,72400.0,81400.0,90400.0,97700.0,104900.0,112100.0,119400.0,552.142857,185.714286,72160.0
110,110,Xenia,Greene,26926.0,74.0,0.0,23.0,10.0,41.0,676.0,...,71200.0,80100.0,89000.0,96200.0,103300.0,110400.0,117500.0,596.594595,82.729730,48110.0
111,111,Zanesville,Muskingum,25346.0,89.0,1.0,23.0,16.0,49.0,1071.0,...,62800.0,70600.0,78400.0,84700.0,91000.0,97300.0,103500.0,438.000000,106.312500,34988.0